# Generated by Django 2.2.6 on 2019-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showings',
            fields=[
                ('showing_pkey', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='last time seen')),
                ('time', models.TimeField(verbose_name='time shown')),
                ('attendance', models.IntegerField()),
                ('showing_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
